apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: simple-api-replicaset

spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: fnobre11/sample-api-k8s:1.1.0
          env:
            - name: PORT
              value: "3000"
            - name: TEST_ENV
              value: "test"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #     httpHeaders:
          #       - name: Content-Type
          #         value: text/plain
          #   periodSeconds: 1
          #   failureThreshold: 2